Feat/v1.12/cilium strict mode
edgelesssys/cilium pull request #32
Opened 2022-08-22 13:49 UTC by 3u13r

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note

```

2022-08-22 17:09 UTC, benschlueter commented on bpf/lib/encap.h
> +#ifdef TUNNEL_MODE
group defines

2022-08-22 17:09 UTC, benschlueter commented on bpf/bpf_host.c
> +#ifndef TUNNEL_MODE
group defines

2022-08-22 17:09 UTC, Kakashiiiiy commented on bpf/lib/strict.h
> +#endif
unused
```suggestion
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on bpf/lib/strict.h
> +
unused
```suggestion
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on bpf/lib/strict.h
> +            }
unused
```suggestion
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on bpf/lib/strict.h
> +#define __WIREGUARD_H_
```suggestion
#ifndef __STRICT_H_
#define __STRICT_H_
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on install/kubernetes/cilium/values.yaml
> +strictModeCIDR: ""
```suggestion
strictModeCIDR: []
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on pkg/datapath/linux/config/utils.go
> +}
unused
```suggestion
```

2022-08-22 17:09 UTC, Kakashiiiiy commented on pkg/datapath/linux/config/utils_test.go
> +}
unused
```suggestion
```

2022-08-23 18:45 UTC, Kakashiiiiy requested changes

2022-08-23 18:45 UTC, Kakashiiiiy commented on bpf/lib/strict.h
> +#endif /* __WIREGUARD_H_ */
can we delete this `#endif`?

2022-08-23 18:45 UTC, Kakashiiiiy commented on pkg/datapath/linux/config/config.go
> +				cDefinesMap["LB4_SRC_RANGE_MAP_SIZE"] = fmt.Sprintf("%d", lbmap.SourceRange4Map.MapInfo.MaxEntries)
unnecessary change

2022-08-23 18:45 UTC, Kakashiiiiy commented on pkg/datapath/linux/config/config.go
> +				cDefinesMap["LB6_SRC_RANGE_MAP_SIZE"] = fmt.Sprintf("%d", lbmap.SourceRange6Map.MapInfo.MaxEntries)
unnecessary change

2022-08-23 18:45 UTC, Kakashiiiiy commented on pkg/datapath/linux/config/config.go
> +			cDefinesMap["IPV4_SNAT_EXCLUSION_DST_CIDR"] = fmt.Sprintf("%#x", byteorder.NetIPv4ToHost32(cidr.IP))
unnecessary change

2022-08-24 09:15 UTC, 3u13r commented on bpf/lib/strict.h
> +#endif /* __WIREGUARD_H_ */
Nope

2022-08-26 12:50 UTC, Kakashiiiiy approved these changes

2022-08-30 15:25 UTC, closed without merging